/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.baeldung.petstore.client.api;

import com.baeldung.petstore.client.model.Item;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-03-22T20:47:42.687-07:00")

@Api(value = "inventory", description = "the inventory API")
public interface InventoryApi {

    @ApiOperation(value = "List Inventory items", nickname = "inventoryGet", notes = "Get all inventory items ", response = Item.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "List of items", response = Item.class) })
    @RequestMapping(value = "/inventory",
        method = RequestMethod.GET)
    ResponseEntity<Item> inventoryGet();


    @ApiOperation(value = "Add to inventory", nickname = "inventoryPost", notes = "Add to inventory ", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Add new item") })
    @RequestMapping(value = "/inventory",
        method = RequestMethod.POST)
    ResponseEntity<Void> inventoryPost(@ApiParam(value = ""  )  @Valid @RequestBody Item body);

}
